name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Create .env file
        run: |
          touch .env
          echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env
      - name: Test Coverage
        run: npm run coverage
        env:
          NODE_ENV: production
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
